default_language_version:
    python: python3.13

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-toml
  -   id: check-yaml
      args:
      -   --unsafe
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: local
  hooks:
    - id: format
      name: format and sort imports
      entry: just format
      language: system
      types: [python]
      pass_filenames: false
    - id: lint
      name: lint and type check
      entry: just lint
      language: system
      types: [python]
      pass_filenames: false

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
    - id: conventional-pre-commit
      name: checks commit message
      stages: [commit-msg]
      args: [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test, .git/COMMIT_MSG]
