services:
  pubsub:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --project fastpubsub-pubsub-local --host-port 0.0.0.0:8085
    environment:
      - CLOUDSDK_CORE_PROJECT=fastpubsub-pubsub-local
    volumes:
      - pubsub_data:/data
    ports:
      - 8085:8085
    security_opt:
      - no-new-privileges:true

  fastpubsub:
    build: .
    volumes:
      - ./:/src
      - /src/.venv/
    network_mode: host
    tty: true

volumes:
  pubsub_data:
