name: Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  UV_LINK_MODE: "copy"
  UV_PYTHON_VERSION: "3.12"

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup just command
        uses: extractions/setup-just@v3
        with:
          just-version: '1.43.0'
      - name: Install uv command
        uses: astral-sh/setup-uv@v7
      - name: Install base python with doc dependencies
        run: just init-group $UV_PYTHON_VERSION docs
      - name: Build docs
        run: just build-docs
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/site
      - uses: actions/deploy-pages@v4
        id: deployment
