name: Quality Checks

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  quality_gate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        run: pip install uv

      - name: Set up Python ${{ matrix.python-version }}
        run: |
          uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-groups --all-extras

      - name: Run quality checks
        run: |
          uv venv --allow-existing
          uv run just lint 
          uv run just test 
          uv run just coverage