name: Quality Checks
on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - synchronize

env:
  UV_LINK_MODE: "copy"
  UV_PYTHON_VERSION: "3.12"

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup just command
        uses: extractions/setup-just@v3
        with:
          just-version: '1.43.0'
      - name: Install uv command
        uses: astral-sh/setup-uv@v7
      - name: Install base python with dependencies
        run: just init $UV_PYTHON_VERSION
      - name: Run lint checks
        run: just lint
      - name: Run typo checks
        run: just typo
      - name: Run static analysis checks
        run: just securitize

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup just command
        uses: extractions/setup-just@v3
        with:
            just-version: '1.43.0'
      - name: Build Docker containers
        run: just build --build-arg PYTHON_VERSION=${{ matrix.python-version }}
      - name: Run tests with coverage
        run: just test-cov
